{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\nSecurity issues fixed:\n\t  \n- CVE-2019-11358: Fixed prototype pollution.\n- CVE-2019-12308: Fixed XSS in AdminURLFieldWidget (bsc#1136468)\n- CVE-2019-12781: Fixed incorrect HTTP detection with reverse-proxy connecting via HTTPS (bsc#1139945).\n- CVE-2019-14232: Fixed denial-of-service possibility in ``django.utils.text.Truncator`` (bsc#1142880).\n- CVE-2019-14233: Fixed denial-of-service possibility in ``strip_tags()`` (bsc#1142882).\n- CVE-2019-14234: Fixed SQL injection possibility in key and index lookups for ``JSONField``/``HStoreField`` (bsc#1142883).\n- CVE-2019-14235: Fixed potential memory exhaustion in ``django.utils.encoding.uri_to_iri()`` (bsc#1142885).\n\nNon-security issues fixed:\n\n- Fixed a migration crash on PostgreSQL when adding a check constraint with a contains lookup on DateRangeField or DateTimeRangeField, if the right hand side of an expression is the same type.\n  \nThis update was imported from the openSUSE:Leap:15.1:Update update project.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-2019-1872",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2019_1872-1.json"
			},
			{
				"category": "self",
				"summary": "URL for openSUSE-SU-2019:1872-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW/#5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW"
			},
			{
				"category": "self",
				"summary": "E-Mail link for openSUSE-SU-2019:1872-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW/#5XTP44JEOSNXRVW4JDZXA5XGMBDZLWSW"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1136468",
				"url": "https://bugzilla.suse.com/1136468"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1139945",
				"url": "https://bugzilla.suse.com/1139945"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142880",
				"url": "https://bugzilla.suse.com/1142880"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142882",
				"url": "https://bugzilla.suse.com/1142882"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142883",
				"url": "https://bugzilla.suse.com/1142883"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142885",
				"url": "https://bugzilla.suse.com/1142885"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-11358 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-11358/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-12308 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-12308/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-12781 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-12781/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14232 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14232/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14233 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14233/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14234 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14234/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14235 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14235/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2019-08-14T09:13:06Z",
			"generator": {
				"date": "2019-08-14T09:13:06Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2019:1872-1",
			"initial_release_date": "2019-08-14T09:13:06Z",
			"revision_history": [
				{
					"date": "2019-08-14T09:13:06Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python3-Django-2.2.4-bp151.3.3.1.noarch",
								"product": {
									"name": "python3-Django-2.2.4-bp151.3.3.1.noarch",
									"product_id": "python3-Django-2.2.4-bp151.3.3.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Package Hub 15 SP1",
								"product": {
									"name": "SUSE Package Hub 15 SP1",
									"product_id": "SUSE Package Hub 15 SP1"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-2.2.4-bp151.3.3.1.noarch as component of SUSE Package Hub 15 SP1",
					"product_id": "SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				},
				"product_reference": "python3-Django-2.2.4-bp151.3.3.1.noarch",
				"relates_to_product_reference": "SUSE Package Hub 15 SP1"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-11358",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-11358"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "jQuery before 3.4.0, as used in Drupal, Backdrop CMS, and other products, mishandles jQuery.extend(true, {}, ...) because of Object.prototype pollution. If an unsanitized source object contained an enumerable __proto__ property, it could extend the native Object.prototype.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-11358",
					"url": "https://www.suse.com/security/cve/CVE-2019-11358"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-11358"
		},
		{
			"cve": "CVE-2019-12308",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-12308"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11 before 1.11.21, 2.1 before 2.1.9, and 2.2 before 2.2.2. The clickable Current URL value displayed by the AdminURLFieldWidget displays the provided value without validating it as a safe URL. Thus, an unvalidated value stored in the database, or a value provided as a URL query parameter payload, could result in an clickable JavaScript link.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-12308",
					"url": "https://www.suse.com/security/cve/CVE-2019-12308"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1136468 for CVE-2019-12308",
					"url": "https://bugzilla.suse.com/1136468"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-12308"
		},
		{
			"cve": "CVE-2019-12781",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-12781"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-12781",
					"url": "https://www.suse.com/security/cve/CVE-2019-12781"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1124991 for CVE-2019-12781",
					"url": "https://bugzilla.suse.com/1124991"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1139945 for CVE-2019-12781",
					"url": "https://bugzilla.suse.com/1139945"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-12781"
		},
		{
			"cve": "CVE-2019-14232",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14232"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14232",
					"url": "https://www.suse.com/security/cve/CVE-2019-14232"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142880 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1142880"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1215978 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1215978"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1220358 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1220358"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14232"
		},
		{
			"cve": "CVE-2019-14233",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14233"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14233",
					"url": "https://www.suse.com/security/cve/CVE-2019-14233"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142882 for CVE-2019-14233",
					"url": "https://bugzilla.suse.com/1142882"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14233"
		},
		{
			"cve": "CVE-2019-14234",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14234"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14234",
					"url": "https://www.suse.com/security/cve/CVE-2019-14234"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142883 for CVE-2019-14234",
					"url": "https://bugzilla.suse.com/1142883"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14234"
		},
		{
			"cve": "CVE-2019-14235",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14235"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14235",
					"url": "https://www.suse.com/security/cve/CVE-2019-14235"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142885 for CVE-2019-14235",
					"url": "https://bugzilla.suse.com/1142885"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 15 SP1:python3-Django-2.2.4-bp151.3.3.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-14T09:13:06Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14235"
		}
	]
}
