{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for opencv",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for opencv fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-14491: Fixed an out of bounds read in the function cv:predictOrdered<cv:HaarEvaluator>, leading to DOS (bsc#1144352).\n- CVE-2019-14492: Fixed an out of bounds read/write in the function HaarEvaluator:OptFeature:calc, which leads to denial of service (bsc#1144348).\n- CVE-2019-15939: Fixed a divide-by-zero error in cv:HOGDescriptor:getDescriptorSize (bsc#1149742).\n\nNon-security issue fixed:\n\n- Fixed an issue in opencv-devel that broke builds with 'No rule to make target opencv_calib3d-NOTFOUND' (bsc#1154091).\n\nThis update was imported from the SUSE:SLE-15:Update update project.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-2019-2671",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for openSUSE-SU-2019:2671-1",
				"url": "https://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2019_2671-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for openSUSE-SU-2019:2671-1",
				"url": "https://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1144348",
				"url": "https://bugzilla.suse.com/1144348"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1144352",
				"url": "https://bugzilla.suse.com/1144352"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1149742",
				"url": "https://bugzilla.suse.com/1149742"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1154091",
				"url": "https://bugzilla.suse.com/1154091"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14491 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14491/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14492 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14492/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-15939 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-15939/"
			}
		],
		"title": "Security update for opencv",
		"tracking": {
			"current_release_date": "2019-12-11T09:15:03Z",
			"generator": {
				"date": "2019-12-11T09:15:03Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2019:2671-1",
			"initial_release_date": "2019-12-11T09:15:03Z",
			"revision_history": [
				{
					"date": "2019-12-11T09:15:03Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "libopencv3_3-3.3.1-lp151.6.3.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "opencv-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "opencv-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "opencv-3.3.1-lp151.6.3.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "opencv-devel-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "opencv-devel-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "opencv-devel-3.3.1-lp151.6.3.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "opencv-doc-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "opencv-doc-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "opencv-doc-3.3.1-lp151.6.3.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python2-opencv-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "python2-opencv-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "python2-opencv-3.3.1-lp151.6.3.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python3-opencv-3.3.1-lp151.6.3.1.x86_64",
								"product": {
									"name": "python3-opencv-3.3.1-lp151.6.3.1.x86_64",
									"product_id": "python3-opencv-3.3.1-lp151.6.3.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.1",
								"product": {
									"name": "openSUSE Leap 15.1",
									"product_id": "openSUSE Leap 15.1",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.1"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "libopencv3_3-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "opencv-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "opencv-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "opencv-devel-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "opencv-devel-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "opencv-doc-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "opencv-doc-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python2-opencv-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "python2-opencv-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-opencv-3.3.1-lp151.6.3.1.x86_64 as component of openSUSE Leap 15.1",
					"product_id": "openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
				},
				"product_reference": "python3-opencv-3.3.1-lp151.6.3.1.x86_64",
				"relates_to_product_reference": "openSUSE Leap 15.1"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-14491",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14491"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14491",
					"url": "https://www.suse.com/security/cve/CVE-2019-14491"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1144348 for CVE-2019-14491",
					"url": "https://bugzilla.suse.com/1144348"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1144352 for CVE-2019-14491",
					"url": "https://bugzilla.suse.com/1144352"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-12-11T09:15:03Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14491"
		},
		{
			"cve": "CVE-2019-14492",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14492"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14492",
					"url": "https://www.suse.com/security/cve/CVE-2019-14492"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1144348 for CVE-2019-14492",
					"url": "https://bugzilla.suse.com/1144348"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1144352 for CVE-2019-14492",
					"url": "https://bugzilla.suse.com/1144352"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-12-11T09:15:03Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14492"
		},
		{
			"cve": "CVE-2019-15939",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-15939"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
					"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-15939",
					"url": "https://www.suse.com/security/cve/CVE-2019-15939"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1149742 for CVE-2019-15939",
					"url": "https://bugzilla.suse.com/1149742"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 3.3,
						"baseSeverity": "LOW",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"openSUSE Leap 15.1:libopencv3_3-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-devel-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:opencv-doc-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python2-opencv-3.3.1-lp151.6.3.1.x86_64",
						"openSUSE Leap 15.1:python3-opencv-3.3.1-lp151.6.3.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-12-11T09:15:03Z",
					"details": "low"
				}
			],
			"title": "CVE-2019-15939"
		}
	]
}
