{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "\nThis update for python-Django fixes the following security issues:\n\n- Prevent Denial-of-service possibility by filling session store. (bsc#937522, CVE-2015-5143)\n- Prevent Header injection possibility. (bsc#937523, CVE-2015-5144)\n- A remote denial of service (resource exhaustion) attack against the django session store\n  was fixed in Python Django.  This might have allowed remote attackers to exhaust existing\n  web sessions. (bsc#941587, CVE-2015-5963)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-Storage-1.0-2015-743",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2015_1815-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2015:1815-1",
				"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151815-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2015:1815-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-October/001644.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 937522",
				"url": "https://bugzilla.suse.com/937522"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 937523",
				"url": "https://bugzilla.suse.com/937523"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 941587",
				"url": "https://bugzilla.suse.com/941587"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-5143 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-5143/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-5144 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-5144/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-5963 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-5963/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2015-10-15T02:36:44Z",
			"generator": {
				"date": "2015-10-15T02:36:44Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2015:1815-1",
			"initial_release_date": "2015-10-15T02:36:44Z",
			"revision_history": [
				{
					"date": "2015-10-15T02:36:44Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.6.11-8.1.noarch",
								"product": {
									"name": "python-Django-1.6.11-8.1.noarch",
									"product_id": "python-Django-1.6.11-8.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 1.0",
								"product": {
									"name": "SUSE Enterprise Storage 1.0",
									"product_id": "SUSE Enterprise Storage 1.0",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:1.0"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.6.11-8.1.noarch as component of SUSE Enterprise Storage 1.0",
					"product_id": "SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
				},
				"product_reference": "python-Django-1.6.11-8.1.noarch",
				"relates_to_product_reference": "SUSE Enterprise Storage 1.0"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2015-5143",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-5143"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The session backends in Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (session store consumption) via multiple requests with unique session keys.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-5143",
					"url": "https://www.suse.com/security/cve/CVE-2015-5143"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 937522 for CVE-2015-5143",
					"url": "https://bugzilla.suse.com/937522"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2015-10-15T02:36:44Z",
					"details": "important"
				}
			],
			"title": "CVE-2015-5143"
		},
		{
			"cve": "CVE-2015-5144",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-5144"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-5144",
					"url": "https://www.suse.com/security/cve/CVE-2015-5144"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 937523 for CVE-2015-5144",
					"url": "https://bugzilla.suse.com/937523"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2015-10-15T02:36:44Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-5144"
		},
		{
			"cve": "CVE-2015-5963",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-5963"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "contrib.sessions.middleware.SessionMiddleware in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to contrib.auth.views.logout, which triggers the creation of an empty session record.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-5963",
					"url": "https://www.suse.com/security/cve/CVE-2015-5963"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 941587 for CVE-2015-5963",
					"url": "https://bugzilla.suse.com/941587"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2015-10-15T02:36:44Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-5963"
		}
	]
}
