{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-dnspython",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-dnspython fixes the following issues:\n\n- CVE-2023-29483: Fixed an issue that allowed remote attackers to\n  interfere with DNS name resolution (bsc#1222693).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2024-2605,SUSE-SLE-Module-Public-Cloud-12-2024-2605",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2024_2605-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2024:2605-1",
				"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242605-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2024:2605-1",
				"url": "https://lists.suse.com/pipermail/sle-updates/2024-July/036118.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1222693",
				"url": "https://bugzilla.suse.com/1222693"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-29483 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-29483/"
			}
		],
		"title": "Security update for python-dnspython",
		"tracking": {
			"current_release_date": "2024-07-25T09:43:52Z",
			"generator": {
				"date": "2024-07-25T09:43:52Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2024:2605-1",
			"initial_release_date": "2024-07-25T09:43:52Z",
			"revision_history": [
				{
					"date": "2024-07-25T09:43:52Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-dnspython-1.12.0-9.13.1.noarch",
								"product": {
									"name": "python-dnspython-1.12.0-9.13.1.noarch",
									"product_id": "python-dnspython-1.12.0-9.13.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-dnspython-1.12.0-9.13.1.noarch",
								"product": {
									"name": "python3-dnspython-1.12.0-9.13.1.noarch",
									"product_id": "python3-dnspython-1.12.0-9.13.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Linux Enterprise Module for Public Cloud 12",
								"product": {
									"name": "SUSE Linux Enterprise Module for Public Cloud 12",
									"product_id": "SUSE Linux Enterprise Module for Public Cloud 12",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:sle-module-public-cloud:12"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-dnspython-1.12.0-9.13.1.noarch as component of SUSE Linux Enterprise Module for Public Cloud 12",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 12:python-dnspython-1.12.0-9.13.1.noarch"
				},
				"product_reference": "python-dnspython-1.12.0-9.13.1.noarch",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-dnspython-1.12.0-9.13.1.noarch as component of SUSE Linux Enterprise Module for Public Cloud 12",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 12:python3-dnspython-1.12.0-9.13.1.noarch"
				},
				"product_reference": "python3-dnspython-1.12.0-9.13.1.noarch",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-29483",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-29483"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "eventlet before 0.35.2, as used in dnspython before 2.6.0, allows remote attackers to interfere with DNS name resolution by quickly sending an invalid packet from the expected IP address and source port, aka a \"TuDoor\" attack. In other words, dnspython does not have the preferred behavior in which the DNS name resolution algorithm would proceed, within the full time window, in order to wait for a valid packet. NOTE: dnspython 2.6.0 is unusable for a different reason that was addressed in 2.6.1.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Linux Enterprise Module for Public Cloud 12:python-dnspython-1.12.0-9.13.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python3-dnspython-1.12.0-9.13.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-29483",
					"url": "https://www.suse.com/security/cve/CVE-2023-29483"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1222693 for CVE-2023-29483",
					"url": "https://bugzilla.suse.com/1222693"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Linux Enterprise Module for Public Cloud 12:python-dnspython-1.12.0-9.13.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-dnspython-1.12.0-9.13.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE Linux Enterprise Module for Public Cloud 12:python-dnspython-1.12.0-9.13.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-dnspython-1.12.0-9.13.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-07-25T09:43:52Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2023-29483"
		}
	]
}
