{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "critical"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\n  - CVE-2024-53907: Fixed denial-of-service in django.utils.html.strip_tags() (bsc#1234232)\n  - CVE-2024-53908: Fixed SQL injection in HasKey(lhs, rhs) on Oracle (bsc#1234231)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2024-4285,SUSE-SLE-Module-Packagehub-Subpackages-15-SP6-2024-4285,openSUSE-SLE-15.6-2024-4285",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2024_4285-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2024:4285-1",
				"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20244285-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2024:4285-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-December/019986.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1234231",
				"url": "https://bugzilla.suse.com/1234231"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1234232",
				"url": "https://bugzilla.suse.com/1234232"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2024-53907 page",
				"url": "https://www.suse.com/security/cve/CVE-2024-53907/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2024-53908 page",
				"url": "https://www.suse.com/security/cve/CVE-2024-53908/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2024-12-11T08:30:20Z",
			"generator": {
				"date": "2024-12-11T08:30:20Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2024:4285-1",
			"initial_release_date": "2024-12-11T08:30:20Z",
			"revision_history": [
				{
					"date": "2024-12-11T08:30:20Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-Django-4.2.11-150600.3.12.1.noarch",
								"product": {
									"name": "python311-Django-4.2.11-150600.3.12.1.noarch",
									"product_id": "python311-Django-4.2.11-150600.3.12.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
								"product": {
									"name": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
									"product_id": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:packagehub:15:sp6"
									}
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.6",
								"product": {
									"name": "openSUSE Leap 15.6",
									"product_id": "openSUSE Leap 15.6",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.6"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-Django-4.2.11-150600.3.12.1.noarch as component of SUSE Linux Enterprise Module for Package Hub 15 SP6",
					"product_id": "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch"
				},
				"product_reference": "python311-Django-4.2.11-150600.3.12.1.noarch",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Package Hub 15 SP6"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-Django-4.2.11-150600.3.12.1.noarch as component of openSUSE Leap 15.6",
					"product_id": "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
				},
				"product_reference": "python311-Django-4.2.11-150600.3.12.1.noarch",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-53907",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-53907"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. The strip_tags() method and striptags template filter are subject to a potential denial-of-service attack via certain inputs containing large sequences of nested incomplete HTML entities.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
					"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-53907",
					"url": "https://www.suse.com/security/cve/CVE-2024-53907"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1234232 for CVE-2024-53907",
					"url": "https://bugzilla.suse.com/1234232"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-12-11T08:30:20Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2024-53907"
		},
		{
			"cve": "CVE-2024-53908",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-53908"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup, when an Oracle database is used, is subject to SQL injection if untrusted data is used as an lhs value. (Applications that use the jsonfield.has_key lookup via __ are unaffected.)",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
					"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-53908",
					"url": "https://www.suse.com/security/cve/CVE-2024-53908"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1234231 for CVE-2024-53908",
					"url": "https://bugzilla.suse.com/1234231"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 9.1,
						"baseSeverity": "CRITICAL",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
						"version": "3.1"
					},
					"products": [
						"SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.12.1.noarch",
						"openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.12.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-12-11T08:30:20Z",
					"details": "critical"
				}
			],
			"title": "CVE-2024-53908"
		}
	]
}
