{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\n- CVE-2024-27351: Align the patch with the upstream one and make it more robust. (bsc#1220358)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "HPE-Helion-OpenStack-8-2024-1141,SUSE-2024-1141,SUSE-OpenStack-Cloud-8-2024-1141,SUSE-OpenStack-Cloud-Crowbar-8-2024-1141",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2024_1141-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2024:1141-1",
				"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20241141-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2024:1141-1",
				"url": "https://lists.suse.com/pipermail/sle-updates/2024-April/034881.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1220358",
				"url": "https://bugzilla.suse.com/1220358"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2024-27351 page",
				"url": "https://www.suse.com/security/cve/CVE-2024-27351/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2024-04-08T09:32:16Z",
			"generator": {
				"date": "2024-04-08T09:32:16Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2024:1141-1",
			"initial_release_date": "2024-04-08T09:32:16Z",
			"revision_history": [
				{
					"date": "2024-04-08T09:32:16Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.11.29-3.62.1.noarch",
								"product": {
									"name": "python-Django-1.11.29-3.62.1.noarch",
									"product_id": "python-Django-1.11.29-3.62.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
								"product": {
									"name": "venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
									"product_id": "venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django-1.11.29-3.62.1.noarch",
								"product": {
									"name": "python3-Django-1.11.29-3.62.1.noarch",
									"product_id": "python3-Django-1.11.29-3.62.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
								"product": {
									"name": "venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
									"product_id": "venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "HPE Helion OpenStack 8",
								"product": {
									"name": "HPE Helion OpenStack 8",
									"product_id": "HPE Helion OpenStack 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:hpe-helion-openstack:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 8",
								"product": {
									"name": "SUSE OpenStack Cloud 8",
									"product_id": "SUSE OpenStack Cloud 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:8"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud Crowbar 8",
								"product": {
									"name": "SUSE OpenStack Cloud Crowbar 8",
									"product_id": "SUSE OpenStack Cloud Crowbar 8",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:8"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.62.1.noarch as component of HPE Helion OpenStack 8",
					"product_id": "HPE Helion OpenStack 8:python-Django-1.11.29-3.62.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.62.1.noarch",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch as component of HPE Helion OpenStack 8",
					"product_id": "HPE Helion OpenStack 8:venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch"
				},
				"product_reference": "venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
				"relates_to_product_reference": "HPE Helion OpenStack 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.62.1.noarch as component of SUSE OpenStack Cloud 8",
					"product_id": "SUSE OpenStack Cloud 8:python-Django-1.11.29-3.62.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.62.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch as component of SUSE OpenStack Cloud 8",
					"product_id": "SUSE OpenStack Cloud 8:venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch"
				},
				"product_reference": "venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 8"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.29-3.62.1.noarch as component of SUSE OpenStack Cloud Crowbar 8",
					"product_id": "SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.62.1.noarch"
				},
				"product_reference": "python-Django-1.11.29-3.62.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 8"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-27351",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-27351"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"HPE Helion OpenStack 8:python-Django-1.11.29-3.62.1.noarch",
					"HPE Helion OpenStack 8:venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
					"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.62.1.noarch",
					"SUSE OpenStack Cloud 8:venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
					"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.62.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-27351",
					"url": "https://www.suse.com/security/cve/CVE-2024-27351"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1220358 for CVE-2024-27351",
					"url": "https://bugzilla.suse.com/1220358"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.62.1.noarch",
						"HPE Helion OpenStack 8:venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.62.1.noarch",
						"SUSE OpenStack Cloud 8:venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.62.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"HPE Helion OpenStack 8:python-Django-1.11.29-3.62.1.noarch",
						"HPE Helion OpenStack 8:venv-openstack-horizon-hpe-x86_64-12.0.5~dev6-14.56.1.noarch",
						"SUSE OpenStack Cloud 8:python-Django-1.11.29-3.62.1.noarch",
						"SUSE OpenStack Cloud 8:venv-openstack-horizon-x86_64-12.0.5~dev6-14.56.1.noarch",
						"SUSE OpenStack Cloud Crowbar 8:python-Django-1.11.29-3.62.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-04-08T09:32:16Z",
					"details": "important"
				}
			],
			"title": "CVE-2024-27351"
		}
	]
}
