{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-grpcio",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-grpcio fixes the following issues:\n\n- CVE-2024-11407: data corruption on servers with transmit zero copy enabled. (bsc#1233821)\n- CVE-2024-7246: HPACK table poisoning by gRPC clients communicating with a HTTP/2 proxy. (bsc#1228919)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2024-4428,SUSE-SLE-Module-Public-Cloud-15-SP4-2024-4428",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2024_4428-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2024:4428-1",
				"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20244428-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2024:4428-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-December/020054.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1228919",
				"url": "https://bugzilla.suse.com/1228919"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1233821",
				"url": "https://bugzilla.suse.com/1233821"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2024-11407 page",
				"url": "https://www.suse.com/security/cve/CVE-2024-11407/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2024-7246 page",
				"url": "https://www.suse.com/security/cve/CVE-2024-7246/"
			}
		],
		"title": "Security update for python-grpcio",
		"tracking": {
			"current_release_date": "2024-12-27T10:16:23Z",
			"generator": {
				"date": "2024-12-27T10:16:23Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2024:4428-1",
			"initial_release_date": "2024-12-27T10:16:23Z",
			"revision_history": [
				{
					"date": "2024-12-27T10:16:23Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.1-150400.9.10.1.aarch64",
								"product": {
									"name": "python311-grpcio-1.60.1-150400.9.10.1.aarch64",
									"product_id": "python311-grpcio-1.60.1-150400.9.10.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.1-150400.9.10.1.i586",
								"product": {
									"name": "python311-grpcio-1.60.1-150400.9.10.1.i586",
									"product_id": "python311-grpcio-1.60.1-150400.9.10.1.i586"
								}
							}
						],
						"category": "architecture",
						"name": "i586"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
								"product": {
									"name": "python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
									"product_id": "python311-grpcio-1.60.1-150400.9.10.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.1-150400.9.10.1.s390x",
								"product": {
									"name": "python311-grpcio-1.60.1-150400.9.10.1.s390x",
									"product_id": "python311-grpcio-1.60.1-150400.9.10.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python311-grpcio-1.60.1-150400.9.10.1.x86_64",
								"product": {
									"name": "python311-grpcio-1.60.1-150400.9.10.1.x86_64",
									"product_id": "python311-grpcio-1.60.1-150400.9.10.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP4",
								"product": {
									"name": "SUSE Linux Enterprise Module for Public Cloud 15 SP4",
									"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:sle-module-public-cloud:15:sp4"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.1-150400.9.10.1.aarch64 as component of SUSE Linux Enterprise Module for Public Cloud 15 SP4",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64"
				},
				"product_reference": "python311-grpcio-1.60.1-150400.9.10.1.aarch64",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.1-150400.9.10.1.ppc64le as component of SUSE Linux Enterprise Module for Public Cloud 15 SP4",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le"
				},
				"product_reference": "python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.1-150400.9.10.1.s390x as component of SUSE Linux Enterprise Module for Public Cloud 15 SP4",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x"
				},
				"product_reference": "python311-grpcio-1.60.1-150400.9.10.1.s390x",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-grpcio-1.60.1-150400.9.10.1.x86_64 as component of SUSE Linux Enterprise Module for Public Cloud 15 SP4",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
				},
				"product_reference": "python311-grpcio-1.60.1-150400.9.10.1.x86_64",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 15 SP4"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2024-11407",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-11407"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "There exists a denial of service through Data corruption in gRPC-C++ - gRPC-C++ servers with transmit zero copy enabled through the channel arg GRPC_ARG_TCP_TX_ZEROCOPY_ENABLED can experience data corruption issues. The data sent by the application may be corrupted before transmission over the network thus leading the receiver to receive an incorrect set of bytes causing RPC requests to fail. We recommend upgrading past commit e9046b2bbebc0cb7f5dc42008f807f6c7e98e791",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-11407",
					"url": "https://www.suse.com/security/cve/CVE-2024-11407"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1233821 for CVE-2024-11407",
					"url": "https://bugzilla.suse.com/1233821"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.8,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-12-27T10:16:23Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2024-11407"
		},
		{
			"cve": "CVE-2024-7246",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2024-7246"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "It's possible for a gRPC client communicating with a HTTP/2 proxy to poison the HPACK table between the proxy and the backend such that other clients see failed requests. It's also possible to use this vulnerability to leak other clients HTTP header keys, but not values.\n\nThis occurs because the error status for a misencoded header is not cleared between header reads, resulting in subsequent (incrementally indexed) added headers in the first request being poisoned until cleared from the HPACK table.\n\nPlease update to a fixed version of gRPC as soon as possible. This bug has been fixed in 1.58.3, 1.59.5, 1.60.2, 1.61.3, 1.62.3, 1.63.2, 1.64.3, 1.65.4.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
					"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2024-7246",
					"url": "https://www.suse.com/security/cve/CVE-2024-7246"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1228919 for CVE-2024-7246",
					"url": "https://bugzilla.suse.com/1228919"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.8,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.aarch64",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.ppc64le",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.s390x",
						"SUSE Linux Enterprise Module for Public Cloud 15 SP4:python311-grpcio-1.60.1-150400.9.10.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-12-27T10:16:23Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2024-7246"
		}
	]
}
