{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-paramiko",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-paramiko to 2.0.9 fixes the following issues:\n\nSecurity issue fixed:\n\n- CVE-2018-1000805: Fixed an authentication bypass (bnc#1111151).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2020-1274,SUSE-Storage-5-2020-1274",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2020_1274-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2020:1274-1",
				"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20201274-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2020:1274-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2020-May/006816.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1111151",
				"url": "https://bugzilla.suse.com/1111151"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2018-1000805 page",
				"url": "https://www.suse.com/security/cve/CVE-2018-1000805/"
			}
		],
		"title": "Security update for python-paramiko",
		"tracking": {
			"current_release_date": "2020-05-14T06:08:00Z",
			"generator": {
				"date": "2020-05-14T06:08:00Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2020:1274-1",
			"initial_release_date": "2020-05-14T06:08:00Z",
			"revision_history": [
				{
					"date": "2020-05-14T06:08:00Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-paramiko-2.0.9-3.6.1.noarch",
								"product": {
									"name": "python-paramiko-2.0.9-3.6.1.noarch",
									"product_id": "python-paramiko-2.0.9-3.6.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 5",
								"product": {
									"name": "SUSE Enterprise Storage 5",
									"product_id": "SUSE Enterprise Storage 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-paramiko-2.0.9-3.6.1.noarch as component of SUSE Enterprise Storage 5",
					"product_id": "SUSE Enterprise Storage 5:python-paramiko-2.0.9-3.6.1.noarch"
				},
				"product_reference": "python-paramiko-2.0.9-3.6.1.noarch",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2018-1000805",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2018-1000805"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Paramiko version 2.4.1, 2.3.2, 2.2.3, 2.1.5, 2.0.8, 1.18.5, 1.17.6 contains a Incorrect Access Control vulnerability in SSH server that can result in RCE. This attack appear to be exploitable via network connectivity.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 5:python-paramiko-2.0.9-3.6.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2018-1000805",
					"url": "https://www.suse.com/security/cve/CVE-2018-1000805"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1111151 for CVE-2018-1000805",
					"url": "https://bugzilla.suse.com/1111151"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 5:python-paramiko-2.0.9-3.6.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 9.8,
						"baseSeverity": "CRITICAL",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 5:python-paramiko-2.0.9-3.6.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2020-05-14T06:08:00Z",
					"details": "critical"
				}
			],
			"title": "CVE-2018-1000805"
		}
	]
}
