{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-urllib3",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-urllib3 fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-9740: Fixed CRLF injection issue (bsc#1129071).\n- CVE-2019-11324: Fixed invalid CA certificat verification (bsc#1132900).\n- CVE-2019-11236: Fixed CRLF injection via request parameter (bsc#1132663).\n- CVE-2018-20060: Remove Authorization header when redirecting cross-host (bsc#1119376).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2019-2370,SUSE-SLE-Module-Public-Cloud-12-2019-2370,SUSE-SUSE-Manager-Server-3.2-2019-2370,SUSE-Storage-4-2019-2370,SUSE-Storage-5-2019-2370",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2019:2370-1",
				"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192370-1/"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2019_2370-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2019:2370-1",
				"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192370-1.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1119376",
				"url": "https://bugzilla.suse.com/1119376"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1129071",
				"url": "https://bugzilla.suse.com/1129071"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1132663",
				"url": "https://bugzilla.suse.com/1132663"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1132900",
				"url": "https://bugzilla.suse.com/1132900"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2018-20060 page",
				"url": "https://www.suse.com/security/cve/CVE-2018-20060/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-11236 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-11236/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-11324 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-11324/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-9740 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-9740/"
			}
		],
		"title": "Security update for python-urllib3",
		"tracking": {
			"current_release_date": "2019-09-12T11:30:43Z",
			"generator": {
				"date": "2019-09-12T11:30:43Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2019:2370-1",
			"initial_release_date": "2019-09-12T11:30:43Z",
			"revision_history": [
				{
					"date": "2019-09-12T11:30:43Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-urllib3-1.22-3.14.1.noarch",
								"product": {
									"name": "python-urllib3-1.22-3.14.1.noarch",
									"product_id": "python-urllib3-1.22-3.14.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-urllib3-1.22-3.14.1.noarch",
								"product": {
									"name": "python3-urllib3-1.22-3.14.1.noarch",
									"product_id": "python3-urllib3-1.22-3.14.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Linux Enterprise Module for Public Cloud 12",
								"product": {
									"name": "SUSE Linux Enterprise Module for Public Cloud 12",
									"product_id": "SUSE Linux Enterprise Module for Public Cloud 12",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:sle-module-public-cloud:12"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Manager Server 3.2",
								"product": {
									"name": "SUSE Manager Server 3.2",
									"product_id": "SUSE Manager Server 3.2",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-manager-server:3.2"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 4",
								"product": {
									"name": "SUSE Enterprise Storage 4",
									"product_id": "SUSE Enterprise Storage 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:4"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 5",
								"product": {
									"name": "SUSE Enterprise Storage 5",
									"product_id": "SUSE Enterprise Storage 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-urllib3-1.22-3.14.1.noarch as component of SUSE Linux Enterprise Module for Public Cloud 12",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch"
				},
				"product_reference": "python-urllib3-1.22-3.14.1.noarch",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-urllib3-1.22-3.14.1.noarch as component of SUSE Linux Enterprise Module for Public Cloud 12",
					"product_id": "SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch"
				},
				"product_reference": "python3-urllib3-1.22-3.14.1.noarch",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-urllib3-1.22-3.14.1.noarch as component of SUSE Manager Server 3.2",
					"product_id": "SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
				},
				"product_reference": "python-urllib3-1.22-3.14.1.noarch",
				"relates_to_product_reference": "SUSE Manager Server 3.2"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-urllib3-1.22-3.14.1.noarch as component of SUSE Enterprise Storage 4",
					"product_id": "SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch"
				},
				"product_reference": "python-urllib3-1.22-3.14.1.noarch",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-urllib3-1.22-3.14.1.noarch as component of SUSE Enterprise Storage 5",
					"product_id": "SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch"
				},
				"product_reference": "python-urllib3-1.22-3.14.1.noarch",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2018-20060",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2018-20060"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
					"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2018-20060",
					"url": "https://www.suse.com/security/cve/CVE-2018-20060"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1119376 for CVE-2018-20060",
					"url": "https://bugzilla.suse.com/1119376"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1216275 for CVE-2018-20060",
					"url": "https://bugzilla.suse.com/1216275"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 2.6,
						"baseSeverity": "LOW",
						"vectorString": "CVSS:3.0/AV:A/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-12T11:30:43Z",
					"details": "low"
				}
			],
			"title": "CVE-2018-20060"
		},
		{
			"cve": "CVE-2019-11236",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-11236"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In the urllib3 library through 1.24.1 for Python, CRLF injection is possible if the attacker controls the request parameter.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
					"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-11236",
					"url": "https://www.suse.com/security/cve/CVE-2019-11236"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1129071 for CVE-2019-11236",
					"url": "https://bugzilla.suse.com/1129071"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1132663 for CVE-2019-11236",
					"url": "https://bugzilla.suse.com/1132663"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-12T11:30:43Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-11236"
		},
		{
			"cve": "CVE-2019-11324",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-11324"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
					"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-11324",
					"url": "https://www.suse.com/security/cve/CVE-2019-11324"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1132900 for CVE-2019-11324",
					"url": "https://bugzilla.suse.com/1132900"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-12T11:30:43Z",
					"details": "low"
				}
			],
			"title": "CVE-2019-11324"
		},
		{
			"cve": "CVE-2019-9740",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-9740"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the query string after a ? character) followed by an HTTP header or a Redis command. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
					"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
					"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-9740",
					"url": "https://www.suse.com/security/cve/CVE-2019-9740"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1129071 for CVE-2019-9740",
					"url": "https://bugzilla.suse.com/1129071"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1130840 for CVE-2019-9740",
					"url": "https://bugzilla.suse.com/1130840"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1132663 for CVE-2019-9740",
					"url": "https://bugzilla.suse.com/1132663"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Enterprise Storage 4:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Enterprise Storage 5:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python-urllib3-1.22-3.14.1.noarch",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-urllib3-1.22-3.14.1.noarch",
						"SUSE Manager Server 3.2:python-urllib3-1.22-3.14.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-09-12T11:30:43Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-9740"
		}
	]
}
