{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "\nThis update for python-Django fixes the following issues: \n\n- Prevent settings leak in date template filter. (bsc#955412, CVE-2015-8213)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "sleclo50sp3-python-Django-12302",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2016_0040-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2016:0040-1",
				"url": "https://www.suse.com/support/update/announcement/2016/suse-su-20160040-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2016:0040-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2016-January/001782.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 955412",
				"url": "https://bugzilla.suse.com/955412"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-8213 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-8213/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2016-01-07T09:00:29Z",
			"generator": {
				"date": "2016-01-07T09:00:29Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2016:0040-1",
			"initial_release_date": "2016-01-07T09:00:29Z",
			"revision_history": [
				{
					"date": "2016-01-07T09:00:29Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.6.11-13.1.x86_64",
								"product": {
									"name": "python-Django-1.6.11-13.1.x86_64",
									"product_id": "python-Django-1.6.11-13.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 5",
								"product": {
									"name": "SUSE OpenStack Cloud 5",
									"product_id": "SUSE OpenStack Cloud 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:cloud:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.6.11-13.1.x86_64 as component of SUSE OpenStack Cloud 5",
					"product_id": "SUSE OpenStack Cloud 5:python-Django-1.6.11-13.1.x86_64"
				},
				"product_reference": "python-Django-1.6.11-13.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2015-8213",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-8213"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The get_format function in utils/formats.py in Django before 1.7.x before 1.7.11, 1.8.x before 1.8.7, and 1.9.x before 1.9rc2 might allow remote attackers to obtain sensitive application secrets via a settings key in place of a date/time format setting, as demonstrated by SECRET_KEY.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE OpenStack Cloud 5:python-Django-1.6.11-13.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-8213",
					"url": "https://www.suse.com/security/cve/CVE-2015-8213"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 955412 for CVE-2015-8213",
					"url": "https://bugzilla.suse.com/955412"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 5:python-Django-1.6.11-13.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2016-01-07T09:00:29Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-8213"
		}
	]
}
