{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "python39-3.9.7-2.1 on GA media",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "These are all security issues fixed in the python39-3.9.7-2.1 package on the GA media of openSUSE Tumbleweed.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-Tumbleweed-2024-11286",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2024_11286-1.json"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2011-3389 page",
				"url": "https://www.suse.com/security/cve/CVE-2011-3389/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2011-4944 page",
				"url": "https://www.suse.com/security/cve/CVE-2011-4944/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2012-0845 page",
				"url": "https://www.suse.com/security/cve/CVE-2012-0845/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2012-1150 page",
				"url": "https://www.suse.com/security/cve/CVE-2012-1150/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2013-1752 page",
				"url": "https://www.suse.com/security/cve/CVE-2013-1752/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2013-4238 page",
				"url": "https://www.suse.com/security/cve/CVE-2013-4238/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-2667 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-2667/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-4650 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-4650/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-20907 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-20907/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-5010 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-5010/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-9947 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-9947/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-15523 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-15523/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-15801 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-15801/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-8492 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-8492/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-23336 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-23336/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-29921 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-29921/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-3177 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-3177/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-3426 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-3426/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-3733 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-3733/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-3737 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-3737/"
			}
		],
		"title": "python39-3.9.7-2.1 on GA media",
		"tracking": {
			"current_release_date": "2024-06-15T00:00:00Z",
			"generator": {
				"date": "2024-06-15T00:00:00Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2024:11286-1",
			"initial_release_date": "2024-06-15T00:00:00Z",
			"revision_history": [
				{
					"date": "2024-06-15T00:00:00Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python39-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-3.9.7-2.1.aarch64",
									"product_id": "python39-3.9.7-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-32bit-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-32bit-3.9.7-2.1.aarch64",
									"product_id": "python39-32bit-3.9.7-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-curses-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-curses-3.9.7-2.1.aarch64",
									"product_id": "python39-curses-3.9.7-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-dbm-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-dbm-3.9.7-2.1.aarch64",
									"product_id": "python39-dbm-3.9.7-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-idle-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-idle-3.9.7-2.1.aarch64",
									"product_id": "python39-idle-3.9.7-2.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-tk-3.9.7-2.1.aarch64",
								"product": {
									"name": "python39-tk-3.9.7-2.1.aarch64",
									"product_id": "python39-tk-3.9.7-2.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python39-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-3.9.7-2.1.ppc64le",
									"product_id": "python39-3.9.7-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-32bit-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-32bit-3.9.7-2.1.ppc64le",
									"product_id": "python39-32bit-3.9.7-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-curses-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-curses-3.9.7-2.1.ppc64le",
									"product_id": "python39-curses-3.9.7-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-dbm-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-dbm-3.9.7-2.1.ppc64le",
									"product_id": "python39-dbm-3.9.7-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-idle-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-idle-3.9.7-2.1.ppc64le",
									"product_id": "python39-idle-3.9.7-2.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python39-tk-3.9.7-2.1.ppc64le",
								"product": {
									"name": "python39-tk-3.9.7-2.1.ppc64le",
									"product_id": "python39-tk-3.9.7-2.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python39-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-3.9.7-2.1.s390x",
									"product_id": "python39-3.9.7-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-32bit-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-32bit-3.9.7-2.1.s390x",
									"product_id": "python39-32bit-3.9.7-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-curses-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-curses-3.9.7-2.1.s390x",
									"product_id": "python39-curses-3.9.7-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-dbm-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-dbm-3.9.7-2.1.s390x",
									"product_id": "python39-dbm-3.9.7-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-idle-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-idle-3.9.7-2.1.s390x",
									"product_id": "python39-idle-3.9.7-2.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python39-tk-3.9.7-2.1.s390x",
								"product": {
									"name": "python39-tk-3.9.7-2.1.s390x",
									"product_id": "python39-tk-3.9.7-2.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python39-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-3.9.7-2.1.x86_64",
									"product_id": "python39-3.9.7-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-32bit-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-32bit-3.9.7-2.1.x86_64",
									"product_id": "python39-32bit-3.9.7-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-curses-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-curses-3.9.7-2.1.x86_64",
									"product_id": "python39-curses-3.9.7-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-dbm-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-dbm-3.9.7-2.1.x86_64",
									"product_id": "python39-dbm-3.9.7-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-idle-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-idle-3.9.7-2.1.x86_64",
									"product_id": "python39-idle-3.9.7-2.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python39-tk-3.9.7-2.1.x86_64",
								"product": {
									"name": "python39-tk-3.9.7-2.1.x86_64",
									"product_id": "python39-tk-3.9.7-2.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-32bit-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-32bit-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-32bit-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-32bit-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-32bit-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-32bit-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-32bit-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-32bit-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-curses-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-curses-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-curses-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-curses-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-curses-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-curses-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-curses-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-curses-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-dbm-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-dbm-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-dbm-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-dbm-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-dbm-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-dbm-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-dbm-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-dbm-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-idle-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-idle-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-idle-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-idle-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-idle-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-idle-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-idle-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-idle-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-tk-3.9.7-2.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64"
				},
				"product_reference": "python39-tk-3.9.7-2.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-tk-3.9.7-2.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le"
				},
				"product_reference": "python39-tk-3.9.7-2.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-tk-3.9.7-2.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x"
				},
				"product_reference": "python39-tk-3.9.7-2.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-tk-3.9.7-2.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				},
				"product_reference": "python39-tk-3.9.7-2.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2011-3389",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2011-3389"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The SSL protocol, as used in certain configurations in Microsoft Windows and Microsoft Internet Explorer, Mozilla Firefox, Google Chrome, Opera, and other products, encrypts data by using CBC mode with chained initialization vectors, which allows man-in-the-middle attackers to obtain plaintext HTTP headers via a blockwise chosen-boundary attack (BCBA) on an HTTPS session, in conjunction with JavaScript code that uses (1) the HTML5 WebSocket API, (2) the Java URLConnection API, or (3) the Silverlight WebClient API, aka a \"BEAST\" attack.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2011-3389",
					"url": "https://www.suse.com/security/cve/CVE-2011-3389"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 716002 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/716002"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 719047 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/719047"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 725167 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/725167"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 726096 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/726096"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 739248 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/739248"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 739256 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/739256"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 742306 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/742306"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 751718 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/751718"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 759666 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/759666"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 763598 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/763598"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 814655 for CVE-2011-3389",
					"url": "https://bugzilla.suse.com/814655"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 3.7,
						"baseSeverity": "LOW",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2011-3389"
		},
		{
			"cve": "CVE-2011-4944",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2011-4944"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions before changing them after data has been written, which introduces a race condition that allows local users to obtain a username and password by reading this file.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2011-4944",
					"url": "https://www.suse.com/security/cve/CVE-2011-4944"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 754447 for CVE-2011-4944",
					"url": "https://bugzilla.suse.com/754447"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 3.3,
						"baseSeverity": "LOW",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "low"
				}
			],
			"title": "CVE-2011-4944"
		},
		{
			"cve": "CVE-2012-0845",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2012-0845"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "SimpleXMLRPCServer.py in SimpleXMLRPCServer in Python before 2.6.8, 2.7.x before 2.7.3, 3.x before 3.1.5, and 3.2.x before 3.2.3 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via an XML-RPC POST request that contains a smaller amount of data than specified by the Content-Length header.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2012-0845",
					"url": "https://www.suse.com/security/cve/CVE-2012-0845"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 747125 for CVE-2012-0845",
					"url": "https://bugzilla.suse.com/747125"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2012-0845"
		},
		{
			"cve": "CVE-2012-1150",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2012-1150"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python before 2.6.8, 2.7.x before 2.7.3, 3.x before 3.1.5, and 3.2.x before 3.2.3 computes hash values without restricting the ability to trigger hash collisions predictably, which allows context-dependent attackers to cause a denial of service (CPU consumption) via crafted input to an application that maintains a hash table.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2012-1150",
					"url": "https://www.suse.com/security/cve/CVE-2012-1150"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 751718 for CVE-2012-1150",
					"url": "https://bugzilla.suse.com/751718"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 755383 for CVE-2012-1150",
					"url": "https://bugzilla.suse.com/755383"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 826682 for CVE-2012-1150",
					"url": "https://bugzilla.suse.com/826682"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2012-1150"
		},
		{
			"cve": "CVE-2013-1752",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2013-1752"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "** REJECT ** Various versions of Python do not properly restrict readline calls, which allows remote attackers to cause a denial of service (memory consumption) via a long string, related to (1) httplib - fixed in 2.7.4, 2.6.9, and 3.3.3; (2) ftplib - fixed in 2.7.6, 2.6.9, 3.3.3; (3) imaplib - not yet fixed in 2.7.x, fixed in 2.6.9, 3.3.3; (4) nntplib - fixed in 2.7.6, 2.6.9, 3.3.3; (5) poplib - not yet fixed in 2.7.x, fixed in 2.6.9, 3.3.3; and (6) smtplib - not yet fixed in 2.7.x, fixed in 2.6.9, not yet fixed in 3.3.x. NOTE: this was REJECTed because it is incompatible with CNT1 \"Independently Fixable\" in the CVE Counting Decisions.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2013-1752",
					"url": "https://www.suse.com/security/cve/CVE-2013-1752"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 856835 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/856835"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 856836 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/856836"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 863741 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/863741"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 885882 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/885882"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 898572 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/898572"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 912739 for CVE-2013-1752",
					"url": "https://bugzilla.suse.com/912739"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2013-1752"
		},
		{
			"cve": "CVE-2013-4238",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2013-4238"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The ssl.match_hostname function in the SSL module in Python 2.6 through 3.4 does not properly handle a '\\0' character in a domain name in the Subject Alternative Name field of an X.509 certificate, which allows man-in-the-middle attackers to spoof arbitrary SSL servers via a crafted certificate issued by a legitimate Certification Authority, a related issue to CVE-2009-2408.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2013-4238",
					"url": "https://www.suse.com/security/cve/CVE-2013-4238"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 834601 for CVE-2013-4238",
					"url": "https://bugzilla.suse.com/834601"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 839107 for CVE-2013-4238",
					"url": "https://bugzilla.suse.com/839107"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 882915 for CVE-2013-4238",
					"url": "https://bugzilla.suse.com/882915"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 912739 for CVE-2013-4238",
					"url": "https://bugzilla.suse.com/912739"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2013-4238"
		},
		{
			"cve": "CVE-2014-2667",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-2667"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-2667",
					"url": "https://www.suse.com/security/cve/CVE-2014-2667"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 871152 for CVE-2014-2667",
					"url": "https://bugzilla.suse.com/871152"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-2667"
		},
		{
			"cve": "CVE-2014-4650",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-4650"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The CGIHTTPServer module in Python 2.7.5 and 3.3.4 does not properly handle URLs in which URL encoding is used for path separators, which allows remote attackers to read script source code or conduct directory traversal attacks and execute unintended code via a crafted character sequence, as demonstrated by a %2f separator.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-4650",
					"url": "https://www.suse.com/security/cve/CVE-2014-4650"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 856835 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/856835"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 856836 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/856836"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 863741 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/863741"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 885882 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/885882"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 898572 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/898572"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 912739 for CVE-2014-4650",
					"url": "https://bugzilla.suse.com/912739"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-4650"
		},
		{
			"cve": "CVE-2019-20907",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-20907"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-20907",
					"url": "https://www.suse.com/security/cve/CVE-2019-20907"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1174091 for CVE-2019-20907",
					"url": "https://bugzilla.suse.com/1174091"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-20907"
		},
		{
			"cve": "CVE-2019-5010",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-5010"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-5010",
					"url": "https://www.suse.com/security/cve/CVE-2019-5010"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1122191 for CVE-2019-5010",
					"url": "https://bugzilla.suse.com/1122191"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1126909 for CVE-2019-5010",
					"url": "https://bugzilla.suse.com/1126909"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-5010"
		},
		{
			"cve": "CVE-2019-9947",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-9947"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-9947",
					"url": "https://www.suse.com/security/cve/CVE-2019-9947"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1130840 for CVE-2019-9947",
					"url": "https://bugzilla.suse.com/1130840"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1136184 for CVE-2019-9947",
					"url": "https://bugzilla.suse.com/1136184"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1155094 for CVE-2019-9947",
					"url": "https://bugzilla.suse.com/1155094"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1201559 for CVE-2019-9947",
					"url": "https://bugzilla.suse.com/1201559"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-9947"
		},
		{
			"cve": "CVE-2020-15523",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-15523"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-15523",
					"url": "https://www.suse.com/security/cve/CVE-2020-15523"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1173745 for CVE-2020-15523",
					"url": "https://bugzilla.suse.com/1173745"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.8,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2020-15523"
		},
		{
			"cve": "CVE-2020-15801",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-15801"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-15801",
					"url": "https://www.suse.com/security/cve/CVE-2020-15801"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1174241 for CVE-2020-15801",
					"url": "https://bugzilla.suse.com/1174241"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 9.8,
						"baseSeverity": "CRITICAL",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "critical"
				}
			],
			"title": "CVE-2020-15801"
		},
		{
			"cve": "CVE-2020-8492",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-8492"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-8492",
					"url": "https://www.suse.com/security/cve/CVE-2020-8492"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1162367 for CVE-2020-8492",
					"url": "https://bugzilla.suse.com/1162367"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2020-8492"
		},
		{
			"cve": "CVE-2021-23336",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-23336"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The package python/cpython from 0 and before 3.6.13, from 3.7.0 and before 3.7.10, from 3.8.0 and before 3.8.8, from 3.9.0 and before 3.9.2 are vulnerable to Web Cache Poisoning via urllib.parse.parse_qsl and urllib.parse.parse_qs by using a vector called parameter cloaking. When the attacker can separate query parameters using a semicolon (;), they can cause a difference in the interpretation of the request between the proxy (running with default configuration) and the server. This can result in malicious requests being cached as completely safe ones, as the proxy would usually not see the semicolon as a separator, and therefore would not include it in a cache key of an unkeyed parameter.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-23336",
					"url": "https://www.suse.com/security/cve/CVE-2021-23336"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1182179 for CVE-2021-23336",
					"url": "https://bugzilla.suse.com/1182179"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1182379 for CVE-2021-23336",
					"url": "https://bugzilla.suse.com/1182379"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1182433 for CVE-2021-23336",
					"url": "https://bugzilla.suse.com/1182433"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2021-23336"
		},
		{
			"cve": "CVE-2021-29921",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-29921"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Python before 3,9,5, the ipaddress library mishandles leading zero characters in the octets of an IP address string. This (in some situations) allows attackers to bypass access control that is based on IP addresses.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-29921",
					"url": "https://www.suse.com/security/cve/CVE-2021-29921"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185706 for CVE-2021-29921",
					"url": "https://bugzilla.suse.com/1185706"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 8.6,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-29921"
		},
		{
			"cve": "CVE-2021-3177",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-3177"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-3177",
					"url": "https://www.suse.com/security/cve/CVE-2021-3177"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1181126 for CVE-2021-3177",
					"url": "https://bugzilla.suse.com/1181126"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.9,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2021-3177"
		},
		{
			"cve": "CVE-2021-3426",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-3426"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-3426",
					"url": "https://www.suse.com/security/cve/CVE-2021-3426"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1183374 for CVE-2021-3426",
					"url": "https://bugzilla.suse.com/1183374"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2021-3426"
		},
		{
			"cve": "CVE-2021-3733",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-3733"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-3733",
					"url": "https://www.suse.com/security/cve/CVE-2021-3733"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1189287 for CVE-2021-3733",
					"url": "https://bugzilla.suse.com/1189287"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "low"
				}
			],
			"title": "CVE-2021-3733"
		},
		{
			"cve": "CVE-2021-3737",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-3737"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
					"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-3737",
					"url": "https://www.suse.com/security/cve/CVE-2021-3737"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1189241 for CVE-2021-3737",
					"url": "https://bugzilla.suse.com/1189241"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python39-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-32bit-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-curses-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-dbm-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-idle-3.9.7-2.1.x86_64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.aarch64",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.ppc64le",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.s390x",
						"openSUSE Tumbleweed:python39-tk-3.9.7-2.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2021-3737"
		}
	]
}
