{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "python-Django-1.9.12-1.1 on GA media",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "These are all security issues fixed in the python-Django-1.9.12-1.1 package on the GA media of openSUSE Tumbleweed.",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-Tumbleweed-2024-10066",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2024_10066-1.json"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-3982 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-3982/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-5145 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-5145/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-5963 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-5963/"
			}
		],
		"title": "python-Django-1.9.12-1.1 on GA media",
		"tracking": {
			"current_release_date": "2024-06-15T00:00:00Z",
			"generator": {
				"date": "2024-06-15T00:00:00Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2024:10066-1",
			"initial_release_date": "2024-06-15T00:00:00Z",
			"revision_history": [
				{
					"date": "2024-06-15T00:00:00Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.9.12-1.1.aarch64",
								"product": {
									"name": "python-Django-1.9.12-1.1.aarch64",
									"product_id": "python-Django-1.9.12-1.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.9.12-1.1.ppc64le",
								"product": {
									"name": "python-Django-1.9.12-1.1.ppc64le",
									"product_id": "python-Django-1.9.12-1.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.9.12-1.1.s390x",
								"product": {
									"name": "python-Django-1.9.12-1.1.s390x",
									"product_id": "python-Django-1.9.12-1.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.9.12-1.1.x86_64",
								"product": {
									"name": "python-Django-1.9.12-1.1.x86_64",
									"product_id": "python-Django-1.9.12-1.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.9.12-1.1.aarch64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64"
				},
				"product_reference": "python-Django-1.9.12-1.1.aarch64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.9.12-1.1.ppc64le as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le"
				},
				"product_reference": "python-Django-1.9.12-1.1.ppc64le",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.9.12-1.1.s390x as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x"
				},
				"product_reference": "python-Django-1.9.12-1.1.s390x",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.9.12-1.1.x86_64 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
				},
				"product_reference": "python-Django-1.9.12-1.1.x86_64",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2015-3982",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-3982"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The session.flush function in the cached_db backend in Django 1.8.x before 1.8.2 does not properly flush the session, which allows remote attackers to hijack user sessions via an empty string in the session key.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-3982",
					"url": "https://www.suse.com/security/cve/CVE-2015-3982"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 932265 for CVE-2015-3982",
					"url": "https://bugzilla.suse.com/932265"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-3982"
		},
		{
			"cve": "CVE-2015-5145",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-5145"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-5145",
					"url": "https://www.suse.com/security/cve/CVE-2015-5145"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 937524 for CVE-2015-5145",
					"url": "https://bugzilla.suse.com/937524"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "important"
				}
			],
			"title": "CVE-2015-5145"
		},
		{
			"cve": "CVE-2015-5963",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-5963"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "contrib.sessions.middleware.SessionMiddleware in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to contrib.auth.views.logout, which triggers the creation of an empty session record.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
					"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-5963",
					"url": "https://www.suse.com/security/cve/CVE-2015-5963"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 941587 for CVE-2015-5963",
					"url": "https://bugzilla.suse.com/941587"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.aarch64",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.ppc64le",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.s390x",
						"openSUSE Tumbleweed:python-Django-1.9.12-1.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2024-06-15T00:00:00Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-5963"
		}
	]
}
